spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hr?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234!!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test7  # H2 접속 정보
#    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

